### ISSUE TITLE
POST Member/Favorite callback 需要成功的資料

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/issue_tainan#25]
新增收藏分類成功後，返回的 data 需要包含剛剛新增的資料，例如 id

![image](https://cloud.githubusercontent.com/assets/4414580/8135878/c6a3c8a4-116c-11e5-83ba-ad23534ad528.png)

這樣才能把新增的 ID 作為後面動作的辨識，
可以省去還要再發送一次請求 Member/Favorite 列表來更新。
![image](https://cloud.githubusercontent.com/assets/4414580/8135934/4e39d678-116d-11e5-9112-4d9875e711b7.png)

步驟3需要有ID

**Comment by paulho1223** [comment]
已更新API
