### ISSUE TITLE
POST Member/StoreBoxes 一次可以複選分類的寫入

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/issue_tainan#26]
因為這邊是複選，所以可以將這個店家收藏在不同的分類裡

![image](https://cloud.githubusercontent.com/assets/4414580/8136702/96dcc0d6-1170-11e5-8648-41a980b04ce6.png)

這邊可能會使用陣列拋送，例如
使用者選一個 array(100);
使用者選兩個 array(100, 199);

目前只能放入一個分類喔

![image](https://cloud.githubusercontent.com/assets/4414580/8136670/583fd368-1170-11e5-841c-c4d3867c4988.png)

**Comment by paulho1223** [comment]
已更新API
