### ISSUE TITLE
POST Member/Login 登入時效問題

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/issue_tainan#27]
![image](https://cloud.githubusercontent.com/assets/4414580/8142623/abc1d366-11b5-11e5-82cf-a2170654b58c.png)

目前返回只有 token，是否可以添加該 token 過期時間，
這樣我這邊的主機在使用者登入後，到了快要過期之前會再發送替換 token

**Comment by paulho1223** [comment]
只有要丟Token都會更新有效時間延長二十分鐘

**Comment by fdjkgh580** [comment]
@paulho1223

問一下喔，
如果說使用者閒置超過 20 分鐘，
當他做介面上的任何點動作，
可能會發動AJAX或是直接連結到下一個頁面，
這時候令牌應該是失效的。但是在我這邊的會員登入是 "還在登入中"，
會產生 "還在登入中但是API的令牌無效"。好比使用者登入中，但是資料庫卻連不到。

若要解決這個問題，我這邊的

想法一、
1) 發送某個功能的 API 後，接收都要驗證 status 是否為 "令牌無效" (好像是202?)
2) 如果錯誤是令牌無效，我需要在背景讓 API 去做登入驗證的動作
3) API 重新取回新令牌
4) 重複再去發動步驟 1 的同樣請求
但我覺得步驟4這樣會重複步驟1的動作。總共發動3次請求。

想法二、
延長 API 令牌的有效期間，目前 20 分鐘可能太短了。登入有效時間需要小於 API 令牌有效時間。
這可能比較省事？
登入成功後只發動所需的請求 1 次。

想法三、
添加令牌的有效時間
1) 我這邊的主機在每次發動某項功能請求，不發送API檢查是否過期，直接檢查登入時記錄在 session的令牌期效是否過期
2) 若過期，先做重新申請令牌(目前沒有這個API)或是重新登入
3) 取得新令牌以後，才繼續發動功能請求。
這個檢查當遇到令牌過期的時候，發動2次請求。

我覺得想法三是比較好理解的。若搭配延長令牌時間如24小時內直到登出，應該可以減少問題。

或是你那邊有比較好的建議嗎？

**Comment by paulho1223** [comment]
你把Token視為是Session就好了
我的作法跟Session的原理是相同的

所以當你取得Token失效 表示使用者要重新登入了

**Comment by fdjkgh580** [comment]
可以參考一下 OAUTH 2.0 的 token_access 實作部分。

![image](https://cloud.githubusercontent.com/assets/4414580/8199226/3e45a772-14e4-11e5-9171-780691c38225.png)

因為 API Token 失效不代表使用者登出，這兩個實作上是不同的。

Token 失效應該是要重新取得 Token 而不是讓使用者去做登出的動作。

**Comment by paulho1223** [comment]
如圖所示  是要回傳二個 token 給你 一個是 Access Token 另一個 Refresh Token
你Access Token 為何會失效?  另一個Refresh Token 何時會失效?
這些我不知道你有沒有想過耶
我之所以不回傳 Refresh Token , 因為我可以控制 Access Token 失效的時間
所以我先前有提到 只要你有Token了 你都要傳送Token給我  這樣Token就不會失效了 
(跟Session原理相同 只要你一直在網頁上活動 Session是不會失效才對)
(若還發生  我就要開始記錄你所傳來的Request了)

**Comment by fdjkgh580** [comment]
我不太明白你說的跟 Session 原理相同指的是什麼？Session 只是一個伺服器暫存的功能，跟 Cookie 一樣。

Access Token & Refresh Token 的過期時效我不是寫API，所以決定全不在我這裡。
但我這裡可以決定的是使用者何時登出~~~~

我這邊的 Session 跟你的 Session 會完全不一樣。因為有兩台主機喔。
我這邊有A伺服器主機，使用者登入資訊記錄在我這台 A主機的 Session。
API 的B主機，Session 紀錄什麼我這邊也不會清楚呀..

目前需要的是 API Token  失效不等於使用者登出阿...
但我從現在情況，我要怎麼取得新 Token ？

**Comment by paulho1223** [comment]
Session有時間的? 你不知道嗎?  一般都是20分鐘
簡單點  你只要有接到Token後  之後的所有API都要帶上Token
這樣Token就不會失效了

**Comment by fdjkgh580** [comment]
我這裡的 Session 不是20分鐘。各大網站的 Session 也不會只有 20分鐘這麼短呀...
像Gmail 也沒有只有20分鐘這麼短呀....

那可以控制。各台主機 Session 設定都不一樣，可以手動去設定。
有些便宜的雲端主機還不給調整你知道嗎？
API 的 session 過期時效不可能要每個對應的主機也要設定跟 API 時間一樣對吧?

我現在要解決的是使用者 "閒置" 狀態的問題。

**Comment by fdjkgh580** [comment]
建議可以參照 OAUTH 2.0 的設計模式，因為這是目前大型社群常用的設計模式，比較不會有問題。

**Comment by paulho1223** [comment]
我現在考量的不是 "網站"，以後APP也會用到
既然使用者"閒置"過久, 表示他已離開座位或不再瀏覽本網站, 本來就該登出而不是一直佔著
且Session是佔主機的記憶體,  不是使用者的, 釋放是必要的

**Comment by fdjkgh580** [comment]
我覺得....API設計應該要完全不關心使用者是否要登出這件事情。
API 那塊應該是負責好建立 token 、取消 token、更新 token 這些事情...
至於前端、手機要怎麼運，那是開發者的事情，鬆耦合~~~~~鬆耦合~~~~~鬆耦合~~~~~

**Comment by paulho1223** [comment]
好吧　那我再加個機制讓你好作業吧
（我是不覺得那樣會更好做　　我都要你傳TOKEN了　且你也增加我工作量　哈）

**Comment by fdjkgh580** [comment]
阿.....你該不會要自己開工吧！？如果你要從頭刻的話那還是算了，不然會太久。
是說用 composer 應該就已經有 OAUTH 2.0之類實作的 API認證機制了，直接拿來裝就可以啦...
但我不知道你那邊是怎麼開發的SO......
先緩緩，這問題先暫時擱著...

**Comment by fdjkgh580** [comment]
不然我就用 javascript 每幾分鐘拋一次請求但不接收這樣好了，雖然浪費了前端資源，但等以後有時間在來說這部份好了。

**Comment by fdjkgh580** [comment]
TOKEN 是還好，因為現在接的各家API都要有TOKEN，大多也採用 OAUTH 2.0 的機制在跑所以也習慣了
