### ISSUE TITLE
DELETE Member/StoreBoxes 的令牌不通過

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/issue_tainan#28]
我在測試 DELETE 的指令會出現 TOKEN 無法通過的訊息。
但在 POST 的時候不會有問題喔。

![image](https://cloud.githubusercontent.com/assets/4414580/8142818/8c44a78a-11be-11e5-9fde-bfb08ef452fd.png)

DELETE 會返回

![image](https://cloud.githubusercontent.com/assets/4414580/8142810/20f56eba-11be-11e5-8a47-a60c8cef5de0.png)

**Comment by paulho1223** [comment]
兩個request隔多久才測?
我這邊做法是你只有要丟Token  我就會更新Token有效時間
現在有效時間為二十分鐘哦
