### ISSUE TITLE
POST Member/CheckEmail 出現錯誤

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/issue_tainan#29]
![image](https://cloud.githubusercontent.com/assets/4414580/8199270/0d35aea6-14e5-11e5-9234-a67c8f4ed54d.png)

這邊應該是GET不是POST，因為屬於查詢確認的方法？

出現這段訊息

![image](https://cloud.githubusercontent.com/assets/4414580/8199468/31b0feb8-14e8-11e5-9365-6b67803c98c1.png)

操作類別 mysql 主機禁用了, 可以換成PDO看看

**Comment by paulho1223** [comment]
POST or GET 都可以取得 訊息已拿除
