### ISSUE TITLE
優惠券缺少欄位

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/issue_tainan#31]
![image](https://cloud.githubusercontent.com/assets/4414580/9155098/418e018e-3edf-11e5-9936-b971e0ffa1c4.png)

需要欄位
地點
圖片

**Comment by paulho1223** [comment]
新增二個參數 addresses & vipimg
資料範例如下:
"addresses":[{"address":"臺北市中正區八德路１段asdf","city":"臺北市","county":"中正區","road":"八德路１段","addr":"asdf"}],"vipimg":"upload\/201508150149370_b.jpg"}

**Comment by fdjkgh580** [comment]
@paulho1223 
API 文件需要更新喔，目前還沒更新

**Comment by fdjkgh580** [comment]
圖檔位置在 http://522.solola.info
