### ISSUE TITLE
會員集點卡需要補上資料，確定欄位是否正確抓到

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/issue_tainan#32]
![image](https://cloud.githubusercontent.com/assets/4414580/9155276/8b05eb28-3ee5-11e5-8947-48c9ee42d615.png)

**Comment by paulho1223** [comment]
抓 29.	Member/VIP 取得VIP店家
collect_point 點數
stopdt 期限日期
vipimg 圖

**Comment by paulho1223** [comment]
文件已更新
