### ISSUE TITLE
城市卡需要有資料確保有抓到值

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/issue_tainan#33]
![image](https://cloud.githubusercontent.com/assets/4414580/9155288/ccb47f8a-3ee5-11e5-851b-a6342d4b0787.png)

**Comment by paulho1223** [comment]
設定成功會多回傳圖
範例如下:
"cityimg":"upload\/201508150137340_b.jpg"

**Comment by fdjkgh580** [comment]
@paulho1223 

版面城市卡圖片一開始就需要存在了，所以不能等成功才回傳圖片。
一開始進入會被半透明遮罩蓋住，但圖片已經存在了喔

**Comment by paulho1223** [comment]
文件已更新
