### ISSUE TITLE
取得店家類別 格式未修改

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/issue_tainan#34]
![image](https://cloud.githubusercontent.com/assets/4414580/9292553/3112f10c-4434-11e5-825e-4b063250f079.png)

返回的是ID與title 與格式不同
![image](https://cloud.githubusercontent.com/assets/4414580/9292566/bb0ee5a0-4434-11e5-89bd-6e02f7100031.png)

**Comment by paulho1223** [comment]
文件已更新
