### ISSUE TITLE
Member/User recent_schedule 沒有其他欄位

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/issue_tainan#36]
GET Member/User
![image](https://cloud.githubusercontent.com/assets/4414580/9305076/c75a5d48-4520-11e5-974a-6c206cc62906.png)

![image](https://cloud.githubusercontent.com/assets/4414580/9305089/e368cbd2-4520-11e5-8df9-fcc939f0c789.png)

**Comment by paulho1223** [comment]
文件已更新
