### ISSUE TITLE
GET Store/Search 缺少欄位

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/issue_tainan#38]
![image](https://cloud.githubusercontent.com/assets/4414580/9307557/a7366e2e-4531-11e5-8899-34d7f8c9d851.png)

**Comment by paulho1223** [comment]
文件已更新

4, 5 抓相簿前二筆
6 是啥 看不清楚
7, 8, 9 我不知道那要幹嘛  該放啥

**Comment by fdjkgh580** [comment]
@paulho1223 

6 是收藏該店家的人數
789 是店家設定的超連結

**Comment by paulho1223** [comment]
文件已更新

但789, 只有 9 FB粉絲頁, 其他二個沒有了
但多了店家官網和EMAIL

**Comment by fdjkgh580** [comment]
欄位與版面不同，我後續再確認看是要哪種的
