### ISSUE TITLE
GET Member/StoreBoxes 文件中的欄位需要修正

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/issue_tainan#39]
文件中的
![image](https://cloud.githubusercontent.com/assets/4414580/9697425/888d1ea4-53bf-11e5-81b8-827a881f3aa8.png)

實際資料
![image](https://cloud.githubusercontent.com/assets/4414580/9697426/9f1f4d54-53bf-11e5-8263-8decf78edce1.png)

**Comment by paulho1223** [comment]
文件已更新
