### ISSUE TITLE
GET Member/HistoryStore 取得瀏覽店家需要添加資料

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/issue_tainan#41]
![image](https://cloud.githubusercontent.com/assets/4414580/9702615/90bfa68e-5499-11e5-8108-97e6da7f5134.png)

可以指定 今天、昨天、七天內、一個月內
需要有封面欄位

用在這邊：
![image](https://cloud.githubusercontent.com/assets/4414580/9702640/d6b6a9c0-549a-11e5-9770-6f8ca557aeed.png)

**Comment by paulho1223** [comment]
文件已更新

**Comment by fdjkgh580** [comment]
@paulho1223 

目前這樣只能輸入單一日期，那如果須要一段區間如: 七天之內，格式要怎麼指定呢？

![image](https://cloud.githubusercontent.com/assets/4414580/9895599/e5b077c8-5c63-11e5-85e9-d4fb1344f5c9.png)

**Comment by paulho1223** [comment]
文件已更新

改成 startday, endday

**Comment by fdjkgh580** [comment]
@paulho1223 
帶入參數後，會是沒有數據
![image](https://cloud.githubusercontent.com/assets/4414580/10153992/b1c182e6-6694-11e5-9851-c1e46e467acd.png)

**Comment by paulho1223** [comment]
因為你start & end 都同一天呀  這個不叫做區間好嗎
我已加入判斷了  同一天 我只會以 Start 為主

**Comment by fdjkgh580** [comment]
問題是不管帶入什麼都是空的啊....

**Comment by fdjkgh580** [comment]
OK
