### ISSUE TITLE
需要取得城市卡列表

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/issue_tainan#42]
目前僅有取得單筆城市卡
Member/OwnStore 

需要可以一次取得多筆的方法
用在這裡
![image](https://cloud.githubusercontent.com/assets/4414580/9898316/e9fe0028-5c83-11e5-894f-647d9bff1dc6.png)

**Comment by paulho1223** [comment]
文件已更新

用34.	Member/OwnStore 取得擁有城市卡清單 這支抓吧
