### ISSUE TITLE
需要判斷的開通欄位

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/issue_tainan#43]
![image](https://cloud.githubusercontent.com/assets/4414580/9899064/e125d4ac-5c89-11e5-9b04-2686a6fcdf36.png)

1. 是否開通VIP功能
2. 是否開通我的程式收集冊
3. 是否開通優惠卡

API如 
GET &cl=member&at=storeboxes

**Comment by paulho1223** [comment]
文件已更新

多了 citycard, openvip, opencoupon
