### ISSUE TITLE
GET store/search 列表需要的條件

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/issue_tainan#44]
#38 
須要搜尋的相關欄位

- 縣市
- 關鍵字
- 特色
- 貼心服務
- (標籤項目) 
 - 預設
 - 人氣排行
 - 更新時間
 - 收藏最多
 - 城市蒐集
 - 優惠餐券
 - 連鎖加盟

![image](https://cloud.githubusercontent.com/assets/4414580/10036332/a4b2cc92-61d8-11e5-8541-a0e725972ffd.png)

**Comment by paulho1223** [comment]
文件已更新

特色, 貼心服務 和 所有分類 都是用 category 傳字串
請用逗號分隔, 中間不要夾空白

**Comment by fdjkgh580** [comment]
@paulho1223  不限的話要傳什麼辨識？目前有三種不限~

**Comment by fdjkgh580** [comment]
@paulho1223 座位數的話目前是區間，需要修改格式

**Comment by paulho1223** [comment]
不限 跟 不勾選條件有啥不一樣?  若你要帶傳就傳0吧
座位區間已更新上文件了
包廂選項已改到貼心服務裡了
