### ISSUE TITLE
29.Member/VIP 取得VIP店家

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/issue_tainan#47]
文件寫的回傳格式稍有不同
![image](https://cloud.githubusercontent.com/assets/4414580/10127192/7e5045c4-65d0-11e5-96b5-21cd8c83bd6c.png)

![image](https://cloud.githubusercontent.com/assets/4414580/10127196/87732108-65d0-11e5-9359-d866893f0e3a.png)

**Comment by paulho1223** [comment]
文件已更新
