### ISSUE TITLE
Member/Coupon 取得優惠卷

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/issue_tainan#48]
文件返回的格式與實際稍微不同

![image](https://cloud.githubusercontent.com/assets/4414580/10127849/5c15f462-65db-11e5-8890-7e656e41fe0b.png)

![image](https://cloud.githubusercontent.com/assets/4414580/10127852/644ccbe2-65db-11e5-8018-5d50da18b5e8.png)

**Comment by paulho1223** [comment]
文件已更新

**Comment by fdjkgh580** [comment]
這部分沒有變更喔～我看還是一樣喔
![image](https://cloud.githubusercontent.com/assets/4414580/11525339/4bcd5158-990d-11e5-8c3b-855c65c5564c.png)

**Comment by paulho1223** [comment]
更新上去了
