### ISSUE TITLE
20.Member/Schedules 取得使用者所有行程

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/issue_tainan#49]
目前缺少的欄位
![image](https://cloud.githubusercontent.com/assets/4414580/10138834/dc763872-6632-11e5-9151-e63af1c6f0e1.png)

三個圖片分別是

- 是否開通VIP功能
- 是否開通我的程式收集冊
- 是否開通優惠卡

如 #43 

然後因為需要點選上面日曆做查詢當天的行程，
所以需要傳送一個日期，返回查詢結果。

**Comment by paulho1223** [comment]
文件已更新
