### ISSUE TITLE
7.Store/Search 取得店家 - city_id

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/issue_tainan#54]
發生錯誤
![image](https://cloud.githubusercontent.com/assets/4414580/10154851/1e3d71b4-669f-11e5-9dc2-f8d4c609bbb5.png)

**Comment by paulho1223** [comment]
已解決

**Comment by fdjkgh580** [comment]
#44 
這樣這部分的 特色, 貼心服務 是不是需要給我個唯一編號？

**Comment by paulho1223** [comment]
特色和貼心服務 請抓以下二個API
2.	Store/SpecialType 取得特色類別
3.	Store/ServiceType 取得其他服務類別
