### ISSUE TITLE
店家餐券欄位

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/issue_tainan#59]
餐券需要的相關欄位

封面
標題
內文
折扣
日期區間
已販售數量
原始價格
現省多少元的價格
![image](https://cloud.githubusercontent.com/assets/4414580/10443907/a3119200-7192-11e5-8f36-62ed23d55139.png)

**Comment by paulho1223** [comment]
文件已更新   32. Store/Tickets 店家餐卷
