### ISSUE TITLE
15.Store/Menus 取得店家菜單

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/issue_tainan#61]
點選類別，可取得當前分類的菜單內容
![image](https://cloud.githubusercontent.com/assets/4414580/10502879/1863e864-7323-11e5-9193-c4f8b172677b.png)

![image](https://cloud.githubusercontent.com/assets/4414580/10502886/2bb9a28c-7323-11e5-9c3c-09fdbbf5133b.png)

**Comment by paulho1223** [comment]
文件已更新
